### ISSUE TITLE
Container cannot start redis after restarting

### ISSUE THREAD

**Issue by hoangsonnguyen** [bitnami/bitnami-docker-redis#123]
**Description**
Container cannot start redis after restarting using the command `docker restart <container_id>`
I think the starting process is stuck in redis_initialize function of libredis.sh file

```
redis_initialize() {
    info "Initializing Redis..."
    # User injected custom configuration
    if [[ -e "$REDIS_BASEDIR/etc/redis.conf" ]]; then
        [[ -e "$REDIS_BASEDIR/etc/redis-default.conf" ]] && rm "${REDIS_BASEDIR}/etc/redis-default.conf"
    else
        debug "Ensuring expected directories/files exist..."
        for dir in "${REDIS_VOLUME}/data" "${REDIS_BASEDIR}/tmp" "${REDIS_LOGDIR}"; do
            ensure_dir_exists "$dir"
            if am_i_root; then
                chown "$REDIS_DAEMON_USER:$REDIS_DAEMON_GROUP" "$dir"
            fi
        done
        mv "$REDIS_BASEDIR/etc/redis-default.conf" "$REDIS_BASEDIR/etc/redis.conf"

        # Redis config
        debug "Setting Redis config file..."
        redis_conf_set dir "${REDIS_VOLUME}/data"
        redis_conf_set logfile "" # Log to stdout
        redis_conf_set pidfile "${REDIS_BASEDIR}/tmp/redis.pid"
        redis_conf_set daemonize yes
        redis_conf_set bind 0.0.0.0 # Allow remote connections
        # Enable AOF https://redis.io/topics/persistence#append-only-file
        # Leave default fsync (every second)
        redis_conf_set appendonly yes
        # Disable RDB persistence, AOF persistence already enabled.
        # Ref: https://redis.io/topics/persistence#interactions-between-aof-and-rdb-persistence
        redis_conf_set save ""
        if [[ -n "$REDIS_PASSWORD" ]]; then
            redis_conf_set requirepass "$REDIS_PASSWORD"
        else
            redis_conf_unset requirepass
        fi
        if [[ -n "$REDIS_DISABLE_COMMANDS" ]]; then
            redis_disable_unsafe_commands
        fi
        # Configure Replication mode
        if [[ -n "$REDIS_REPLICATION_MODE" ]]; then
            redis_configure_replication
        fi
    fi
}

```

**Steps to reproduce the issue:**
In docker-compose file
```
version: "3.2"
services:
  redis-test-dev:
      image: 'bitnami/redis:latest'
      container_name: redisdev
      user: '1001'
      restart: on-failure
      security_opt:
        -  apparmor=unconfined
      ports:
        - "6879:6379"
      env_file:
        - ./env/.dev.env
      volumes:
       - ./redis-persistence-dev:/bitnami/redis/data
```

**Describe the results you received:**

> Welcome to the Bitnami redis container
> Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
> Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
> Send us your feedback at containers@bitnami.com
> 
> INFO  ==> ** Starting Redis setup **
> DEBUG ==> Validating settings in REDIS_* env vars..
> INFO  ==> Initializing Redis...
> DEBUG ==> Ensuring expected directories/files exist...
> DEBUG ==> Setting Redis config file...
> INFO  ==> ** Redis setup finished! **
> 
> INFO  ==> ** Starting Redis **
> 1:C 10 Nov 02:15:00.735 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> 1:C 10 Nov 02:15:00.793 # Redis version=4.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
> 1:C 10 Nov 02:15:00.793 # Configuration loaded
>                 _._                                                  
>            _.-``__ ''-._                                             
>       _.-``    `.  `_.  ''-._           Redis 4.0.11 (00000000/0) 64 bit
>   .-`` .-```.  ```\/    _.,_ ''-._                                   
>  (    '      ,       .-`  | `,    )     Running in standalone mode
>  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
>  |    `-._   `._    /     _.-'    |     PID: 1
>   `-._    `-._  `-./  _.-'    _.-'                                   
>  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
>  |    `-._`-._        _.-'_.-'    |           http://redis.io        
>   `-._    `-._`-.__.-'_.-'    _.-'                                   
>  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
>  |    `-._`-._        _.-'_.-'    |                                  
>   `-._    `-._`-.__.-'_.-'    _.-'                                   
>       `-._    `-.__.-'    _.-'                                       
>           `-._        _.-'                                           
>               `-.__.-'                                               
> 
> 1:M 10 Nov 02:15:00.807 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
> 1:M 10 Nov 02:15:00.807 # Server initialized
> 1:M 10 Nov 02:15:00.807 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
> 1:M 10 Nov 02:15:00.808 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
> 1:M 10 Nov 02:15:00.989 * DB loaded from append only file: 0.182 seconds
> 1:M 10 Nov 02:15:00.989 * Ready to accept connections
> 1:signal-handler (1541816114) Received SIGTERM scheduling shutdown...
> 1:M 10 Nov 02:15:14.926 # User requested shutdown...
> 1:M 10 Nov 02:15:14.926 * Calling fsync() on the AOF file.
> 1:M 10 Nov 02:15:14.926 * Removing the pid file.
> 1:M 10 Nov 02:15:14.926 # Redis is now ready to exit, bye bye...
> 
> INFO  ==> ** Starting Redis setup **
> DEBUG ==> Validating settings in REDIS_* env vars..
> INFO  ==> Initializing Redis...
> 
> INFO  ==> ** Starting Redis setup **
> DEBUG ==> Validating settings in REDIS_* env vars..
> INFO  ==> Initializing Redis...
> 

**Describe the results you expected:**

I would like to have redis up after restarting the container

**Version**

- Output of `docker version`:

```
Docker version 18.06.0-ce, build 0ffa825
```

- Output of `docker info`:

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 13
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-38-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.64GiB
Name: pc
ID: LLES:CGN2:VEDL:5WVS:DMMS:FRD3:ZKZO:LBOE:VGGL:2LXH:VREM:Y6TI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.15rc1
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017

```

**Comment by juan131** [comment]
Hi @hoangsonnguyen 

Could you add the env. variable below? It'll increase the verbosity of the logs and we might get more information about the reason why Redis can't be restarted

```
BITNAMI_DEBUG=true
```

**Comment by hoangsonnguyen** [comment]
Here are the logs after I added 

> Welcome to the Bitnami redis container
> Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
> Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
> Send us your feedback at containers@bitnami.com
> redisdev          | 
> redisdev          | Welcome to the Bitnami redis container
> redisdev          | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
> redisdev          | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
> redisdev          | Send us your feedback at containers@bitnami.com
> redisdev          | 
> redisdev          | INFO  ==> ** Starting Redis setup **
> redisdev          | DEBUG ==> Validating settings in REDIS_* env vars..
> redisdev          | INFO  ==> Initializing Redis...
> redisdev          | DEBUG ==> Ensuring expected directories/files exist...
> redisdev          | DEBUG ==> Setting Redis config file...
> redisdev          | INFO  ==> ** Redis setup finished! **
> redisdev          | 
> redisdev          | INFO  ==> ** Starting Redis **
> redisdev          | 1:C 10 Nov 02:15:00.735 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> redisdev          | 1:C 10 Nov 02:15:00.793 # Redis version=4.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
> redisdev          | 1:C 10 Nov 02:15:00.793 # Configuration loaded
> redisdev          |                 _._                                                  
> redisdev          |            _.-``__ ''-._                                             
> redisdev          |       _.-``    `.  `_.  ''-._           Redis 4.0.11 (00000000/0) 64 bit
> redisdev          |   .-`` .-```.  ```\/    _.,_ ''-._                                   
> redisdev          |  (    '      ,       .-`  | `,    )     Running in standalone mode
> redisdev          |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
> redisdev          |  |    `-._   `._    /     _.-'    |     PID: 1
> redisdev          |   `-._    `-._  `-./  _.-'    _.-'                                   
> redisdev          |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
> redisdev          |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
> redisdev          |   `-._    `-._`-.__.-'_.-'    _.-'                                   
> redisdev          |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
> redisdev          |  |    `-._`-._        _.-'_.-'    |                                  
> redisdev          |   `-._    `-._`-.__.-'_.-'    _.-'                                   
> redisdev          |       `-._    `-.__.-'    _.-'                                       
> redisdev          |           `-._        _.-'                                           
> redisdev          |               `-.__.-'                                               
> redisdev          | 
> redisdev          | 1:M 10 Nov 02:15:00.807 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
> redisdev          | 1:M 10 Nov 02:15:00.807 # Server initialized
> redisdev          | 1:M 10 Nov 02:15:00.807 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
> redisdev          | 1:M 10 Nov 02:15:00.808 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
> redisdev          | 1:M 10 Nov 02:15:00.989 * DB loaded from append only file: 0.182 seconds
> redisdev          | 1:M 10 Nov 02:15:00.989 * Ready to accept connections
> redisdev          | 1:signal-handler (1541816114) Received SIGTERM scheduling shutdown...
> redisdev          | 1:M 10 Nov 02:15:14.926 # User requested shutdown...
> redisdev          | 1:M 10 Nov 02:15:14.926 * Calling fsync() on the AOF file.
> redisdev          | 1:M 10 Nov 02:15:14.926 * Removing the pid file.
> redisdev          | 1:M 10 Nov 02:15:14.926 # Redis is now ready to exit, bye bye...
> redisdev exited with code 0
> 
> INFO  ==> ** Starting Redis setup **
> DEBUG ==> Validating settings in REDIS_* env vars..
> INFO  ==> Initializing Redis...

**Comment by juan131** [comment]
We just released a new revision of the Docker Image fixing the issue. Could you try using one of the images below?

- **5.0.0-debian-9-r12** 
- **4.0.11-debian-9-r91**
- **5.0.0-ol-7-r12**
- **4.0.11-ol-7-r101**

**Comment by yod527** [comment]
Hello! For me, issue is still there. Using :latest redis container tag. Hash is `f86d0f4741a7`.
I tryed to enable BITNAMI_DEBUG but that didn’t adds any log verbosity. Logs:
```
Welcome to the Bitnami redis container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting Redis setup **
DEBUG ==> Validating settings in REDIS_* env vars..
WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
INFO  ==> Initializing Redis...

Welcome to the Bitnami redis container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting Redis setup **
DEBUG ==> Validating settings in REDIS_* env vars..
WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
INFO  ==> Initializing Redis..
```

**Comment by javsalgar** [comment]
Hi,

Just to confirm. You said in your update that the r12 tag works fine. Could it be that you had the `latest` version cached?

**Comment by yod527** [comment]
@javsalgar Hi. No, i'm actually using docker-compose to do all the stuff. So, i was on :latest tag (image was f86d0f4741a7) and then i switched to r12 directly.

**Comment by juan131** [comment]
That's so weird @yod527 ... Had you pull the latest tag recently?

```bash
$ docker pull bitnami/redis:latest
```

Your latest tag could be pointing to an old tag (previous to `r12`)
